# coding: utf-8

# flake8: noqa
"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.address import Address
from swagger_client.models.address_input import AddressInput
from swagger_client.models.address_type import AddressType
from swagger_client.models.bank_account import BankAccount
from swagger_client.models.bank_account_currency import BankAccountCurrency
from swagger_client.models.bank_account_input import BankAccountInput
from swagger_client.models.business import Business
from swagger_client.models.business_input import BusinessInput
from swagger_client.models.business_type import BusinessType
from swagger_client.models.checkout import Checkout
from swagger_client.models.checkout_status import CheckoutStatus
from swagger_client.models.checkout_type import CheckoutType
from swagger_client.models.collect import Collect
from swagger_client.models.collection_account import CollectionAccount
from swagger_client.models.confirmation import Confirmation
from swagger_client.models.conversion import Conversion
from swagger_client.models.conversion_status import ConversionStatus
from swagger_client.models.country import Country
from swagger_client.models.credit_payment_input import CreditPaymentInput
from swagger_client.models.credit_result import CreditResult
from swagger_client.models.credit_terms import CreditTerms
from swagger_client.models.currency import Currency
from swagger_client.models.debit import Debit
from swagger_client.models.debit_status import DebitStatus
from swagger_client.models.deposit_intent import DepositIntent
from swagger_client.models.fee import Fee
from swagger_client.models.id_confirm_body import IdConfirmBody
from swagger_client.models.id_credit_body import IdCreditBody
from swagger_client.models.inbound import Inbound
from swagger_client.models.inbound_status import InboundStatus
from swagger_client.models.inbound_type import InboundType
from swagger_client.models.individual import Individual
from swagger_client.models.individual_input import IndividualInput
from swagger_client.models.intent import Intent
from swagger_client.models.intent_bank_account_input import IntentBankAccountInput
from swagger_client.models.intent_output_type import IntentOutputType
from swagger_client.models.intent_status import IntentStatus
from swagger_client.models.intent_type import IntentType
from swagger_client.models.intents_payment_body import IntentsPaymentBody
from swagger_client.models.intents_setup_body import IntentsSetupBody
from swagger_client.models.invoice import Invoice
from swagger_client.models.invoice_status import InvoiceStatus
from swagger_client.models.known_participant import KnownParticipant
from swagger_client.models.limit import Limit
from swagger_client.models.link_intent import LinkIntent
from swagger_client.models.organisation import Organisation
from swagger_client.models.organisation_input import OrganisationInput
from swagger_client.models.organisation_type import OrganisationType
from swagger_client.models.outbound import Outbound
from swagger_client.models.outbound_failure_reason import OutboundFailureReason
from swagger_client.models.outbound_paused_reason import OutboundPausedReason
from swagger_client.models.outbound_result import OutboundResult
from swagger_client.models.outbound_status import OutboundStatus
from swagger_client.models.outbound_type import OutboundType
from swagger_client.models.outbounds_refunds_body import OutboundsRefundsBody
from swagger_client.models.outbounds_releases_body import OutboundsReleasesBody
from swagger_client.models.participant_input import ParticipantInput
from swagger_client.models.participant_status import ParticipantStatus
from swagger_client.models.participant_type import ParticipantType
from swagger_client.models.payment_instrument import PaymentInstrument
from swagger_client.models.payment_instrument_status import PaymentInstrumentStatus
from swagger_client.models.payment_instrument_type import PaymentInstrumentType
from swagger_client.models.payment_intent import PaymentIntent
from swagger_client.models.payment_type import PaymentType
from swagger_client.models.person import Person
from swagger_client.models.person_input import PersonInput
from swagger_client.models.person_type import PersonType
from swagger_client.models.project import Project
from swagger_client.models.project_account import ProjectAccount
from swagger_client.models.project_routing_code_type import ProjectRoutingCodeType
from swagger_client.models.project_routing_data import ProjectRoutingData
from swagger_client.models.project_status import ProjectStatus
from swagger_client.models.project_transfer_in import ProjectTransferIn
from swagger_client.models.project_transfer_out import ProjectTransferOut
from swagger_client.models.project_transfers import ProjectTransfers
from swagger_client.models.project_type import ProjectType
from swagger_client.models.refund_input import RefundInput
from swagger_client.models.release_input import ReleaseInput
from swagger_client.models.requirement import Requirement
from swagger_client.models.requirements import Requirements
from swagger_client.models.routing_code_type import RoutingCodeType
from swagger_client.models.session_intent import SessionIntent
from swagger_client.models.settlement import Settlement
from swagger_client.models.settlement_input import SettlementInput
from swagger_client.models.settlement_intent import SettlementIntent
from swagger_client.models.settlement_status import SettlementStatus
from swagger_client.models.settlement_target_input import SettlementTargetInput
from swagger_client.models.settlement_type import SettlementType
from swagger_client.models.setup_intent import SetupIntent
from swagger_client.models.setup_intent_type import SetupIntentType
from swagger_client.models.trade_account import TradeAccount
from swagger_client.models.transfer import Transfer
from swagger_client.models.transfer_input import TransferInput
from swagger_client.models.transfer_result import TransferResult
from swagger_client.models.transfer_source_or_target import TransferSourceOrTarget
from swagger_client.models.transfer_source_or_target_input import TransferSourceOrTargetInput
from swagger_client.models.transfer_status import TransferStatus
from swagger_client.models.transfer_sub_type import TransferSubType
from swagger_client.models.transfer_type import TransferType
from swagger_client.models.v1_participants_body import V1ParticipantsBody
from swagger_client.models.v1_paymentinstruments_body import V1PaymentinstrumentsBody
from swagger_client.models.v1_projects_body import V1ProjectsBody
from swagger_client.models.v1_transfers_body import V1TransfersBody
from swagger_client.models.v1_verifications_body import V1VerificationsBody
from swagger_client.models.verification import Verification
from swagger_client.models.verification_status import VerificationStatus
from swagger_client.models.verification_type import VerificationType
