# coding: utf-8

"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Individual(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date_of_birth': 'str',
        'residential_address': 'Address',
        'shipping_address': 'Address',
        'phone_number': 'str'
    }

    attribute_map = {
        'date_of_birth': 'date_of_birth',
        'residential_address': 'residential_address',
        'shipping_address': 'shipping_address',
        'phone_number': 'phone_number'
    }

    def __init__(self, date_of_birth=None, residential_address=None, shipping_address=None, phone_number=None):  # noqa: E501
        """Individual - a model defined in Swagger"""  # noqa: E501
        self._date_of_birth = None
        self._residential_address = None
        self._shipping_address = None
        self._phone_number = None
        self.discriminator = None
        if date_of_birth is not None:
            self.date_of_birth = date_of_birth
        if residential_address is not None:
            self.residential_address = residential_address
        if shipping_address is not None:
            self.shipping_address = shipping_address
        if phone_number is not None:
            self.phone_number = phone_number

    @property
    def date_of_birth(self):
        """Gets the date_of_birth of this Individual.  # noqa: E501

        The individual's date of birth.  # noqa: E501

        :return: The date_of_birth of this Individual.  # noqa: E501
        :rtype: str
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth):
        """Sets the date_of_birth of this Individual.

        The individual's date of birth.  # noqa: E501

        :param date_of_birth: The date_of_birth of this Individual.  # noqa: E501
        :type: str
        """

        self._date_of_birth = date_of_birth

    @property
    def residential_address(self):
        """Gets the residential_address of this Individual.  # noqa: E501


        :return: The residential_address of this Individual.  # noqa: E501
        :rtype: Address
        """
        return self._residential_address

    @residential_address.setter
    def residential_address(self, residential_address):
        """Sets the residential_address of this Individual.


        :param residential_address: The residential_address of this Individual.  # noqa: E501
        :type: Address
        """

        self._residential_address = residential_address

    @property
    def shipping_address(self):
        """Gets the shipping_address of this Individual.  # noqa: E501


        :return: The shipping_address of this Individual.  # noqa: E501
        :rtype: Address
        """
        return self._shipping_address

    @shipping_address.setter
    def shipping_address(self, shipping_address):
        """Sets the shipping_address of this Individual.


        :param shipping_address: The shipping_address of this Individual.  # noqa: E501
        :type: Address
        """

        self._shipping_address = shipping_address

    @property
    def phone_number(self):
        """Gets the phone_number of this Individual.  # noqa: E501

        The individual's phone number.  # noqa: E501

        :return: The phone_number of this Individual.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this Individual.

        The individual's phone number.  # noqa: E501

        :param phone_number: The phone_number of this Individual.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Individual, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Individual):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
