# coding: utf-8

"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LinkIntent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'created_at': 'str',
        'updated_at': 'str',
        'project_id': 'str',
        '_from': 'KnownParticipant',
        'url': 'str',
        'status': 'IntentStatus',
        'currency': 'Currency',
        'type': 'IntentOutputType',
        'fee_flat': 'int',
        'fee_percentage': 'float',
        'settlements': 'list[SettlementIntent]',
        'redirect_url': 'str',
        'metadata': 'object'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'project_id': 'project_id',
        '_from': 'from',
        'url': 'url',
        'status': 'status',
        'currency': 'currency',
        'type': 'type',
        'fee_flat': 'fee_flat',
        'fee_percentage': 'fee_percentage',
        'settlements': 'settlements',
        'redirect_url': 'redirect_url',
        'metadata': 'metadata'
    }

    def __init__(self, id=None, created_at=None, updated_at=None, project_id=None, _from=None, url=None, status=None, currency=None, type=None, fee_flat=None, fee_percentage=None, settlements=None, redirect_url=None, metadata=None):  # noqa: E501
        """LinkIntent - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created_at = None
        self._updated_at = None
        self._project_id = None
        self.__from = None
        self._url = None
        self._status = None
        self._currency = None
        self._type = None
        self._fee_flat = None
        self._fee_percentage = None
        self._settlements = None
        self._redirect_url = None
        self._metadata = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if project_id is not None:
            self.project_id = project_id
        if _from is not None:
            self._from = _from
        if url is not None:
            self.url = url
        if status is not None:
            self.status = status
        if currency is not None:
            self.currency = currency
        if type is not None:
            self.type = type
        if fee_flat is not None:
            self.fee_flat = fee_flat
        if fee_percentage is not None:
            self.fee_percentage = fee_percentage
        if settlements is not None:
            self.settlements = settlements
        if redirect_url is not None:
            self.redirect_url = redirect_url
        if metadata is not None:
            self.metadata = metadata

    @property
    def id(self):
        """Gets the id of this LinkIntent.  # noqa: E501

        The unique identifier of the created intent.  # noqa: E501

        :return: The id of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LinkIntent.

        The unique identifier of the created intent.  # noqa: E501

        :param id: The id of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this LinkIntent.  # noqa: E501

        The date the payment intent was created.  # noqa: E501

        :return: The created_at of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this LinkIntent.

        The date the payment intent was created.  # noqa: E501

        :param created_at: The created_at of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this LinkIntent.  # noqa: E501

        The date the payment intent was last updated.  # noqa: E501

        :return: The updated_at of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this LinkIntent.

        The date the payment intent was last updated.  # noqa: E501

        :param updated_at: The updated_at of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    @property
    def project_id(self):
        """Gets the project_id of this LinkIntent.  # noqa: E501

        The unique ID of the project which this intent targets.  # noqa: E501

        :return: The project_id of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this LinkIntent.

        The unique ID of the project which this intent targets.  # noqa: E501

        :param project_id: The project_id of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def _from(self):
        """Gets the _from of this LinkIntent.  # noqa: E501


        :return: The _from of this LinkIntent.  # noqa: E501
        :rtype: KnownParticipant
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this LinkIntent.


        :param _from: The _from of this LinkIntent.  # noqa: E501
        :type: KnownParticipant
        """

        self.__from = _from

    @property
    def url(self):
        """Gets the url of this LinkIntent.  # noqa: E501

        The URL that can be shared to complete this payment.  # noqa: E501

        :return: The url of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this LinkIntent.

        The URL that can be shared to complete this payment.  # noqa: E501

        :param url: The url of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def status(self):
        """Gets the status of this LinkIntent.  # noqa: E501


        :return: The status of this LinkIntent.  # noqa: E501
        :rtype: IntentStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this LinkIntent.


        :param status: The status of this LinkIntent.  # noqa: E501
        :type: IntentStatus
        """

        self._status = status

    @property
    def currency(self):
        """Gets the currency of this LinkIntent.  # noqa: E501


        :return: The currency of this LinkIntent.  # noqa: E501
        :rtype: Currency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this LinkIntent.


        :param currency: The currency of this LinkIntent.  # noqa: E501
        :type: Currency
        """

        self._currency = currency

    @property
    def type(self):
        """Gets the type of this LinkIntent.  # noqa: E501


        :return: The type of this LinkIntent.  # noqa: E501
        :rtype: IntentOutputType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LinkIntent.


        :param type: The type of this LinkIntent.  # noqa: E501
        :type: IntentOutputType
        """

        self._type = type

    @property
    def fee_flat(self):
        """Gets the fee_flat of this LinkIntent.  # noqa: E501

        A flat fee to charge the buyer Participant on successfully completing the intent.  Fees are calculated in the following way: (`total` * (1 + `fee_percentage`)) + `fee_flat`.  # noqa: E501

        :return: The fee_flat of this LinkIntent.  # noqa: E501
        :rtype: int
        """
        return self._fee_flat

    @fee_flat.setter
    def fee_flat(self, fee_flat):
        """Sets the fee_flat of this LinkIntent.

        A flat fee to charge the buyer Participant on successfully completing the intent.  Fees are calculated in the following way: (`total` * (1 + `fee_percentage`)) + `fee_flat`.  # noqa: E501

        :param fee_flat: The fee_flat of this LinkIntent.  # noqa: E501
        :type: int
        """

        self._fee_flat = fee_flat

    @property
    def fee_percentage(self):
        """Gets the fee_percentage of this LinkIntent.  # noqa: E501

        A fee percentage to charge the buyer Participant on successfully completing the intent. Fee percentages must be provided as a fraction, ie. 1.5% as 0.015.  Fees are calculated in the following way: (`total` * (1 + `fee_percentage`)) + `fee_flat`.  # noqa: E501

        :return: The fee_percentage of this LinkIntent.  # noqa: E501
        :rtype: float
        """
        return self._fee_percentage

    @fee_percentage.setter
    def fee_percentage(self, fee_percentage):
        """Sets the fee_percentage of this LinkIntent.

        A fee percentage to charge the buyer Participant on successfully completing the intent. Fee percentages must be provided as a fraction, ie. 1.5% as 0.015.  Fees are calculated in the following way: (`total` * (1 + `fee_percentage`)) + `fee_flat`.  # noqa: E501

        :param fee_percentage: The fee_percentage of this LinkIntent.  # noqa: E501
        :type: float
        """

        self._fee_percentage = fee_percentage

    @property
    def settlements(self):
        """Gets the settlements of this LinkIntent.  # noqa: E501

        A list of settlement intents. These describe the line items that will be displayed on the Checkout UI.  # noqa: E501

        :return: The settlements of this LinkIntent.  # noqa: E501
        :rtype: list[SettlementIntent]
        """
        return self._settlements

    @settlements.setter
    def settlements(self, settlements):
        """Sets the settlements of this LinkIntent.

        A list of settlement intents. These describe the line items that will be displayed on the Checkout UI.  # noqa: E501

        :param settlements: The settlements of this LinkIntent.  # noqa: E501
        :type: list[SettlementIntent]
        """

        self._settlements = settlements

    @property
    def redirect_url(self):
        """Gets the redirect_url of this LinkIntent.  # noqa: E501

        The redirect URL supplied at the creation of the intent.  # noqa: E501

        :return: The redirect_url of this LinkIntent.  # noqa: E501
        :rtype: str
        """
        return self._redirect_url

    @redirect_url.setter
    def redirect_url(self, redirect_url):
        """Sets the redirect_url of this LinkIntent.

        The redirect URL supplied at the creation of the intent.  # noqa: E501

        :param redirect_url: The redirect_url of this LinkIntent.  # noqa: E501
        :type: str
        """

        self._redirect_url = redirect_url

    @property
    def metadata(self):
        """Gets the metadata of this LinkIntent.  # noqa: E501

        The metadata that was provided at the creation of the payment intent.  # noqa: E501

        :return: The metadata of this LinkIntent.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this LinkIntent.

        The metadata that was provided at the creation of the payment intent.  # noqa: E501

        :param metadata: The metadata of this LinkIntent.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinkIntent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkIntent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
