# coding: utf-8

"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PersonInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'PersonType',
        'name': 'str',
        'address': 'AddressInput',
        'email': 'str',
        'phone_number': 'str',
        'date_of_birth': 'str'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'address': 'address',
        'email': 'email',
        'phone_number': 'phone_number',
        'date_of_birth': 'date_of_birth'
    }

    def __init__(self, type=None, name=None, address=None, email=None, phone_number=None, date_of_birth=None):  # noqa: E501
        """PersonInput - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._name = None
        self._address = None
        self._email = None
        self._phone_number = None
        self._date_of_birth = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if address is not None:
            self.address = address
        if email is not None:
            self.email = email
        if phone_number is not None:
            self.phone_number = phone_number
        if date_of_birth is not None:
            self.date_of_birth = date_of_birth

    @property
    def type(self):
        """Gets the type of this PersonInput.  # noqa: E501


        :return: The type of this PersonInput.  # noqa: E501
        :rtype: PersonType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PersonInput.


        :param type: The type of this PersonInput.  # noqa: E501
        :type: PersonType
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this PersonInput.  # noqa: E501

        The person's name.  # noqa: E501

        :return: The name of this PersonInput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PersonInput.

        The person's name.  # noqa: E501

        :param name: The name of this PersonInput.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address(self):
        """Gets the address of this PersonInput.  # noqa: E501


        :return: The address of this PersonInput.  # noqa: E501
        :rtype: AddressInput
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this PersonInput.


        :param address: The address of this PersonInput.  # noqa: E501
        :type: AddressInput
        """

        self._address = address

    @property
    def email(self):
        """Gets the email of this PersonInput.  # noqa: E501

        The person's email address.  # noqa: E501

        :return: The email of this PersonInput.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PersonInput.

        The person's email address.  # noqa: E501

        :param email: The email of this PersonInput.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def phone_number(self):
        """Gets the phone_number of this PersonInput.  # noqa: E501

        The person's phone number.  # noqa: E501

        :return: The phone_number of this PersonInput.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this PersonInput.

        The person's phone number.  # noqa: E501

        :param phone_number: The phone_number of this PersonInput.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def date_of_birth(self):
        """Gets the date_of_birth of this PersonInput.  # noqa: E501

        The person's date of birth.  # noqa: E501

        :return: The date_of_birth of this PersonInput.  # noqa: E501
        :rtype: str
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth):
        """Sets the date_of_birth of this PersonInput.

        The person's date of birth.  # noqa: E501

        :param date_of_birth: The date_of_birth of this PersonInput.  # noqa: E501
        :type: str
        """

        self._date_of_birth = date_of_birth

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PersonInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
