# coding: utf-8

"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Requirements(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'country': 'Country',
        'currency': 'BankAccountCurrency',
        'supported': 'bool',
        'requirements': 'list[Requirement]'
    }

    attribute_map = {
        'country': 'country',
        'currency': 'currency',
        'supported': 'supported',
        'requirements': 'requirements'
    }

    def __init__(self, country=None, currency=None, supported=None, requirements=None):  # noqa: E501
        """Requirements - a model defined in Swagger"""  # noqa: E501
        self._country = None
        self._currency = None
        self._supported = None
        self._requirements = None
        self.discriminator = None
        if country is not None:
            self.country = country
        if currency is not None:
            self.currency = currency
        if supported is not None:
            self.supported = supported
        if requirements is not None:
            self.requirements = requirements

    @property
    def country(self):
        """Gets the country of this Requirements.  # noqa: E501


        :return: The country of this Requirements.  # noqa: E501
        :rtype: Country
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this Requirements.


        :param country: The country of this Requirements.  # noqa: E501
        :type: Country
        """

        self._country = country

    @property
    def currency(self):
        """Gets the currency of this Requirements.  # noqa: E501


        :return: The currency of this Requirements.  # noqa: E501
        :rtype: BankAccountCurrency
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Requirements.


        :param currency: The currency of this Requirements.  # noqa: E501
        :type: BankAccountCurrency
        """

        self._currency = currency

    @property
    def supported(self):
        """Gets the supported of this Requirements.  # noqa: E501

        A boolean value denoting whether the request country/currency pair is supported.  # noqa: E501

        :return: The supported of this Requirements.  # noqa: E501
        :rtype: bool
        """
        return self._supported

    @supported.setter
    def supported(self, supported):
        """Sets the supported of this Requirements.

        A boolean value denoting whether the request country/currency pair is supported.  # noqa: E501

        :param supported: The supported of this Requirements.  # noqa: E501
        :type: bool
        """

        self._supported = supported

    @property
    def requirements(self):
        """Gets the requirements of this Requirements.  # noqa: E501

        An array of required fields that must be provided for the country/currency pair.  # noqa: E501

        :return: The requirements of this Requirements.  # noqa: E501
        :rtype: list[Requirement]
        """
        return self._requirements

    @requirements.setter
    def requirements(self, requirements):
        """Sets the requirements of this Requirements.

        An array of required fields that must be provided for the country/currency pair.  # noqa: E501

        :param requirements: The requirements of this Requirements.  # noqa: E501
        :type: list[Requirement]
        """

        self._requirements = requirements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Requirements, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Requirements):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
