# coding: utf-8

"""
    trustshare API

    Welcome to the trustshare API Reference documentation. Here you can find detailed information about the endpoints we provide as well as the shape of entities within the system.  # Environments The trustshare API has two environments, __Sandbox__ and __Live__. Both environments are available under the same endpoint however API Keys and client secrets are prefixed with the environment name. - A __Sandbox__ API Key will be in the format: `sandbox_api_[0-9a-z]`. - A __Live__ API Key will be in the format: `live_api_[0-9a-z]`.  ## Sandbox Our __Sandbox__ environment endeavours to be as close to the __Live__ environment as possible, however, there are a couple of limitations and features which should be noted. - Card payments take around 7 days to settle into accounts. In __Live__ this is generally closer to 2 days. - Manual inbound payments can only be \"faked\" in __Sandbox__ when they are less-than or equal-to `250,000.00`. - Open Banking in __Sandbox__ will always use a \"Mock Bank\" UI to accept the payment.  # noqa: E501

    OpenAPI spec version: 1.0.23
    Contact: support@trustshare.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransferSourceOrTarget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'str',
        'settlement_id': 'str'
    }

    attribute_map = {
        'project_id': 'project_id',
        'settlement_id': 'settlement_id'
    }

    def __init__(self, project_id=None, settlement_id=None):  # noqa: E501
        """TransferSourceOrTarget - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._settlement_id = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if settlement_id is not None:
            self.settlement_id = settlement_id

    @property
    def project_id(self):
        """Gets the project_id of this TransferSourceOrTarget.  # noqa: E501

        The unique ID of the project originating the funds being transfered.  # noqa: E501

        :return: The project_id of this TransferSourceOrTarget.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this TransferSourceOrTarget.

        The unique ID of the project originating the funds being transfered.  # noqa: E501

        :param project_id: The project_id of this TransferSourceOrTarget.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def settlement_id(self):
        """Gets the settlement_id of this TransferSourceOrTarget.  # noqa: E501

        The unique ID of the settlement originating the funds being transfered.  # noqa: E501

        :return: The settlement_id of this TransferSourceOrTarget.  # noqa: E501
        :rtype: str
        """
        return self._settlement_id

    @settlement_id.setter
    def settlement_id(self, settlement_id):
        """Sets the settlement_id of this TransferSourceOrTarget.

        The unique ID of the settlement originating the funds being transfered.  # noqa: E501

        :param settlement_id: The settlement_id of this TransferSourceOrTarget.  # noqa: E501
        :type: str
        """

        self._settlement_id = settlement_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransferSourceOrTarget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferSourceOrTarget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
